platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks!

workspace 'BabylonDemoApp'

target 'BabylonDemoApp' do
  project 'BabylonDemoApp.xcodeproj'
  pod 'PromiseKit'
  pod 'PromiseKit/Foundation'
  pod 'RxSwift'
  pod 'RxCocoa'
end

target 'BabylonDemoAppTests' do
   project 'BabylonDemoApp.xcodeproj'
   pod 'PromiseKit'
   pod 'PromiseKit/Foundation'
end


target 'BabylonApiService' do
  project 'BabylonApiService/BabylonApiService.xcodeproj'
end
